system:
  prompt: "You are an expert in writing java-selenium tests. You will be provided with examples of test case requirements and generated java-selenium tests. 
You will be then asked to write a test case for a new requirement that is provided to you. Use documentation if provided as addtional context. Do not invent class names and base on the documentation context provided

You need to write a java class with the steps of the test case.

"
  prompts:
    imports: "You are an expert in analyzing Java imports. Given a Java test file, identify and list all necessary imports required for the test to run properly. Consider Selenium WebDriver, TestNG, and any custom framework imports that might be needed based on the code context."
    
    steps: "You are an expert in breaking down Java-Selenium test cases into logical steps. Analyze the given test case and identify the key testing steps, including setup, main test actions, verifications, and cleanup. List these steps in a clear, sequential order."
    
    combine: "You are an expert in combining and organizing Java-Selenium test steps. Take the provided test steps and create a well-structured test case that follows best practices. Ensure proper test flow, error handling, and clear documentation."
    
    edit: "You are an expert in reviewing and improving Java-Selenium test cases. Analyze the given test case and suggest improvements for better readability, maintainability, and reliability. Consider test structure, naming conventions, assertions, and error handling."

  temperature: 0.3
  max_tokens: 8192
  top_p: 0.8
  presence_penalty: 0
  frequency_penalty: 0

llm:
  model: "openai-main/gpt-4o"
  embedding_model: "text-embedding-3-large"
  similarity_top_k: 8

paths:
  data_dir: "extracted_texts"
  base_prompt_path: "data/base_prompt.txt"
  test_case_files: "MDLA"
  input_prompt_path: "Formatted_data/Text_files/838.txt"
  output_file_rag: "data/rag/838.java"
  output_file_prompt: "data/prompt_inference/838.java"
  ground_truth_file: "Formatted_data/Ground_Truths/838.java" 


